FROM php:8.2-fpm

# Install dependencies
RUN apt-get update && \
    apt-get install -y \
    libfreetype6-dev libjpeg62-turbo-dev libpng-dev \
    libzip-dev libonig-dev libxml2-dev git unzip curl \
    default-mysql-client \
    libxslt1-dev libcurl4-openssl-dev && \
    docker-php-ext-install -j$(nproc) gd iconv mbstring soap intl zip opcache pdo_mysql bcmath xsl sockets && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /var/www/html

# Clone the Magento repository
RUN git clone https://github.com/magento/magento2.git .

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copy the setup script
COPY ./magento_setup.sh /usr/local/bin/magento_setup.sh
RUN chmod +x /usr/local/bin/magento_setup.sh

# Run the setup script
ENTRYPOINT ["sh", "/usr/local/bin/magento_setup.sh"]

# Expose the PHP-FPM port
EXPOSE 9000

